// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService orchestrates all services
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the current configuration
 */
export function GetConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(2904124381).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTunnelStatus returns the current tunnel status
 */
export function GetTunnelStatus(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(1379396419).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetWebServerStatus returns the current web server status
 */
export function GetWebServerStatus(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(3590057070).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Shutdown performs cleanup when app is shutting down
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(3433198627);
}

/**
 * StartTunnel starts the cloudflared tunnel
 */
export function StartTunnel(manualToken: string): $CancellablePromise<void> {
    return $Call.ByID(2485143129, manualToken);
}

/**
 * StartTunnelWithWebServer starts tunnel and automatically starts web server on success
 */
export function StartTunnelWithWebServer(manualToken: string): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(2799770862, manualToken).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StartWebServer starts the web server
 */
export function StartWebServer(port: number): $CancellablePromise<void> {
    return $Call.ByID(3510568828, port);
}

/**
 * StopAll stops both tunnel and web server
 */
export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(1622073260);
}

/**
 * StopTunnel stops the cloudflared tunnel
 */
export function StopTunnel(): $CancellablePromise<void> {
    return $Call.ByID(354454559);
}

/**
 * StopWebServer stops the web server
 */
export function StopWebServer(): $CancellablePromise<void> {
    return $Call.ByID(436693886);
}

/**
 * UpdateConfig updates the configuration
 */
export function UpdateConfig(config: $models.Config | null): $CancellablePromise<void> {
    return $Call.ByID(2615014218, config);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
