// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config represents the application configuration
 */
export class Config {
    "backendURL": string;
    "tunnelName": string;
    "autoStart": boolean;
    "minimizeToTray": boolean;
    "refreshInterval": number;
    "webServerPort": number;
    "routes": Route[];

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("backendURL" in $$source)) {
            this["backendURL"] = "";
        }
        if (!("tunnelName" in $$source)) {
            this["tunnelName"] = "";
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("minimizeToTray" in $$source)) {
            this["minimizeToTray"] = false;
        }
        if (!("refreshInterval" in $$source)) {
            this["refreshInterval"] = 0;
        }
        if (!("webServerPort" in $$source)) {
            this["webServerPort"] = 0;
        }
        if (!("routes" in $$source)) {
            this["routes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField6_0($$parsedSource["routes"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * Route represents a tunnel route configuration
 */
export class Route {
    "hostname": string;
    "service": string;

    /** Creates a new Route instance. */
    constructor($$source: Partial<Route> = {}) {
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("service" in $$source)) {
            this["service"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Route instance from a string or object.
     */
    static createFrom($$source: any = {}): Route {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Route($$parsedSource as Partial<Route>);
    }
}

// Private type creation functions
const $$createType0 = Route.createFrom;
const $$createType1 = $Create.Array($$createType0);
